### ISSUE TITLE
How to create a new task in Team Planner via API?

### ISSUE THREAD

**Issue by H4mz4-mk** [awork-io/awork#11]
Hey Awork,

I didn't find any way in the documentation to create a new task in Team Planner via the API, can somebody help please?

Best regards

**Comment by nilzzzzzz** [comment]
Hi @H4mz4-mk 

sure. 

You just use this endpoint:
1. https://developers.awork.io/#/Tasks/post_tasks <- create the task and pass a projectId in the model as entityId
2. https://developers.awork.io/#/Tasks/post_tasks_assignusers

Important is that the task needs a start and end date, otherwise it's not shown in the team planner.

Hope i was able to help you.

Nils
