### ISSUE TITLE
API: Example for using fixed token/ API key

### ISSUE THREAD

**Issue by podarcis** [awork-io/awork#15]
I generated a new API key as explained here: https://support.awork.io/en/articles/5415664-client-applications-and-api-keys (see also #13)

However, I miss an example using my client-id and client-secret *without* OAuth2 auth, as explained here: https://developers.awork.io/authentication

> You have two options to access our api. 
> * Fixed token generated in the ui which is permanent valid, but is not user specific. This makes sense for background synchronisation applications. Details explained here.
> * OAuth 2

Could you please provide a simple example how to access the API without any user relation?

**Comment by nilzzzzzz** [comment]
Hi @podarcis,

you just pass the api token as a header:  Authorization: Bearer {access_token}

Can you try that?

Best

Nils

**Comment by podarcis** [comment]
Hi @nilzzzzzz,

Yes, I tried that:

```
$ API_KEY="uW*****REDUCTED******H9" \
    curl -v -H "Authorization: Bearer ${API_KEY}" "https://api.awork.io/api/v1/users?page=1"
...
> GET /api/v1/users?page=1 HTTP/1.1
> Host: api.awork.io
> User-Agent: curl/7.68.0
> Accept: */*
> Authorization: Bearer uW*****REDUCTED******H9
...
{"message":{"description":"Bad token; invalid JSON","code":"unauthorized"}}
```

The API returns code `unauthorized` telling me that the token is invalid and for some reason that there's invalid JSON.

**Comment by nilzzzzzz** [comment]
@podarcis 
are you sure you are not using the client secret? because the api key should be a few times longer like this: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3aWQiOiI3ODM2MGUxMS02N2I5LWU3MTEtODBjMi0wMDE3ZmExMDAzOWIiLCJpaWQiOiJlYTNhMWFmOC03Y2YwLWViXXXTEtYTdhZC1kYzk4NDAyMWM3Y2YiLCJ1aWQiOiJlYTNhMWFmOC03Y2YwLWViMTEtYTdhZC1kYzk4NDAyMWM3Y2YiLCJuYW1lIjoib2twa2tvcGtvcGsiLCJhenAiOiJva3Bra29wa29wayIsInNjb3BlIjoib2ZmbGluZV9hY2Nlc3MiLCJydGlkIjoiXXZWEzYTFhZjgtN2NmMC1lYjExLWE3YWQtZGM5ODQwMjFjN2NmIiwibmJmIjoxNjI3NTcwNTEyLCJleHAiOjQ3NTE3MDgxMTIsImlzcyI6XXXmh0dHBzOi8vbXlocS5pby8iLCJhdWQiOiJhdy1hY2NvdW50cyJ9.dAnB9FIVuh0iazOs5VN-4g2TziCE4q1Msj5-cn26bAc'

(i changed just a few letters now..)

**Comment by podarcis** [comment]
@nilzzzzzz You're right! I missed/skipped the point in the documentation where it says that I need to explicitly add an API-key to my integration. Using the correct key it works as expected. Thanks!

Nevertheless the documentation https://developers.awork.io/authentication might get improved by stating that `API-Key==access-token` in this case.
