### ISSUE TITLE
Searching for name of project task via API

### ISSUE THREAD

**Issue by HalloBeverly** [awork-io/awork#23]
Hi,
I created new projects with the project template via API. The project itself works. Now I have to edit the tasks as well as via API . How do I search for the task name?  /projects/{projectId}/....?
Hope to hear from you soon
Beverly

**Comment by MurmeltierS** [comment]
Pretty sure you should be able to use the [Filtering Options](https://developers.awork.io/filtering) to search for a task inside a project by name. 
e.g.:
`/projects​/{projectId}​/projecttasks?filterBy=name eq 'THE_TASK_NAME'`

**Comment by nilzzzzzz** [comment]
Hey @HalloBeverly,

the solution @MurmeltierS  proposed is the way to go.
If you create the project, make sure to wait a few seconds to request the tasks created by the template, because we add the tasks async.

Best

Nils

**Comment by HalloBeverly** [comment]
Hey Nils, 
it works. I find the projecttasks. Now I have to edit the projecttaks as well as via API. How do I 
1. change the name
2. add member
3. add tags
4. edit the due date and
5. plannend time

Many thanks for your help :-)

Beverly

**Comment by MurmeltierS** [comment]
Via the search you should be able to receive the taskId. (In some context referred as entityId with entityName="tasks")

With this taskId you can:

1. [Change the Name of the Task via PUT](https://openapi.awork.io/#/Tasks/put_tasks__taskId_) at `/tasks/{taskId}`
Just send an JSON object containing the new name in your request body. e.g. `{ 'name':  'THE_NEW_NAME' }`
2. Add a member via [/tasks/assignusers](https://openapi.awork.io/#/Tasks/post_tasks_assignusers)
Please by advised, that this is due to change in 5 days: [Multi User Assignment - 18.09.21 🚨](https://developers.awork.io/api-changes#multi-user-assignment-18-09-21)
3. [Add Tags via the EntityTags/TaskTags Endpoint](https://openapi.awork.io/#/TaskTags/post_tasks__entityId__addtags)
Just POST an array containing the names an (opt.) colors of your desired tags to `​/tasks​/{entityId}​/addtags`
e.g. `[
  {
    "name": "MyTag",
    "color": "coral"
  }
]`
4. Can also be changed via PUT at `/tasks/{taskId}`, [as mentioned in the docs](https://openapi.awork.io/#/Tasks/put_tasks__taskId_)
5. see 4.

Hope this helps.

**Comment by HalloBeverly** [comment]
Perfect ;-) 
Many Thanks

I used the laneOrder to sort the tasks. It is possible to post the task dependency for all projecttasks at once?

**Comment by nilzzzzzz** [comment]
@HalloBeverly no, you need to do it task by task.

Best

Nils
