### ISSUE TITLE
/users Endpoint doesn't seem to work properly

### ISSUE THREAD

**Issue by Cojohnny97** [awork-io/awork#28]
Hello, I have some issues with the '/users' endpoint of the api. I have the feeling this is an internal error because I tried POST and GET requests and both won't work.
For example this is the error response of a POST request:
`{
      code: 'validation-failed',
      description: 'The model sent in the request is invalid. See the validation errors for details.',
      link: 'https://developers.awork.io/',
      space: 'Uranus’ blue glow is down to the methane in its atmosphere, which filters out all the red light.',
      validationErrors: [
        {
          property: '$.accountId',
          message: 'The JSON value could not be converted to System.Guid. Path: $.accountId | LineNumber: 0 | BytePositionInLine: 196.'     
        }
      ]
}`
Here is my trace id: '57e7e231eb8c7ec5'.

**Comment by nilzzzzzz** [comment]
Hi @Cojohnny97,

you pass for the 'accountId' null. This is not valid. The account id is required to connect an account to an user. Can you try the request with a valid account id? 

For the get endpoint: Can you also send me the traceid?

Best

Nils

**Comment by MurmeltierS** [comment]
Hey @nilzzzzzz 
is there any way to create an account via the API to mount to the user, or is this not possible due to Accounts being global and not workspace-scoped? Only the PUT Operation of `/accounts` is documented in the docs?
Or is there a way to create a user not linked to an account yet. I though about the `/invitations` endpoint, but it doesn't seem to be documented.

Would be useful for provisioning purposes. Maybe you can share your thoughts on how to best approach this?

Best regards,

Kevin

**Comment by nilzzzzzz** [comment]
Hey @MurmeltierS ,

it is possible - till now nobody requested access to those endpoints thats the reason they are not public. 
The endpoint `/invitations` is implemented in another micro service which is not added to our public docs yet.

Can you send me a few more infos for the use case by email then i quickly discuss with the team how we proceed. ;) 

Best

Nils

**Comment by MurmeltierS** [comment]
@nilzzzzzz will do
