### ISSUE TITLE
Cannot get API token for personal user

### ISSUE THREAD

**Issue by kain88-de** [awork-io/awork#3]
I use timewarrior [1] as my personal time tracking tool. It works better for me than having to remember using a website. I want to sync my own timetracking with awork. So I would like to write to my own account. Ideally automated. For this I need to use some form of authentication. Your docs [2] you use OAuth2 ,maybe a fixed token works as well but that is unclear from the text. However I cannot create the neseccary client. Everytime I try to I get a 401 error. See attached screenshot. The exact error is `POST https://lawngreen-exotic-foxes.awork.io/api/v1/clientapplications 401 (Unauthorized)`

I assume I'm still lacking some permissions to create client an generate an API key.

What permissions would I need to create a client?
Or alternatively how can I get a token with read/write access to my user only (Similar to the way todoist or gitlab handle this)?

[1] http://timewarrior.net/
[2] https://support.awork.io/hc/en-us/articles/360002815960-Client-Applications-and-API-Keys

![Screenshot_20210308_220749](https://user-images.githubusercontent.com/4302678/110475564-57903e80-80e1-11eb-9d5e-aee8b85af278.png)

**Comment by nilzzzzzz** [comment]
Hi @kain88-de ,
thanks for contacting us.

So in awork we have two possibilities. 
You can do the oauth 2 flow with a specific user or you can create a fixed token. 
In both cases you need to have a client app first. The call failed because you are missing workspace manage permissions. They can set in the permissions settings:
<img width="1645" alt="Screenshot 2021-03-09 at 16 09 26" src="https://user-images.githubusercontent.com/22219385/110492337-60d5d700-80f2-11eb-9133-4c6fd736732a.png">

After that you can generate a bearer token which you can use to create your time-trackings. 

We only have user specific tokens, when you do the oauth flow, otherwise you have a globally valid token which ignores user permissions. This one is usually used for data synchronisation jobs.

I hope i was able to help you!

Nils

**Comment by nilzzzzzz** [comment]
Ah, and for the missing validation in the frontend for the permissions i create a bug ticket on our side.

**Comment by kain88-de** [comment]
BTW it would be nice if I can get a token for my user only without the whole oauth dance

**Comment by RafaRochaS91** [comment]
Refer to [this section ](https://support.awork.io/hc/en-us/articles/360002815960-Client-Applications-and-API-Keys#:~:text=API%20Key%20without%20User%20Authentication).

**Comment by kain88-de** [comment]
I can *write* with that token? I understood the documentation that this one can only be used for reading. Which would make sense. Because why should I be allowed to write data for other users

**Comment by nilzzzzzz** [comment]
With that token you can write. But you can also write for other users, that'S the reason you need workspace permissions.

**Comment by nilzzzzzz** [comment]
You can use the Oauth flow for that. So it is possible. We have no plans right now to create manual user specific tokens.
