### ISSUE TITLE
[Question]: Creating a project from a template resulted in missing project description

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#36]
### What is your question?

Hi 👋🏻 

We are creating projects via the API and one of my colleagues reported that after creation the project description is missing.

This doesn't happen all the time but it's [not the first time](https://github.com/awork-io/awork/issues/33) I got a report like this.

But! This time I have a trace id :-) 

### Do you have a trace id of the call?

2280233ae9839987 or

2628fddf632b2dcb

It's possibly the first one but I'm not completely sure since they are not one second apart.

**Comment by sebastianrosch** [comment]
Hi @timkley thanks for the report. I took a look at the project in this trace id and what I can see from my records is that it was created without a description via the API. The description was then edited several times via our web app.
I cannot find any indication for the project description disappearing after it has been set.
Could you confirm this observation on your end?
If you think that you are sending the description via the API, could you check the project model you're sending to the API to make sure there is no typo in the property names?
Hope this helps.

**Comment by timkley** [comment]
Hi @sebastianrosch,

yes, we are creating the project without a description, that is correct. We expect the description to be populated with the description from the project template (which works most of the time without a problem).

This is the payload we are sending:

```
            [
                'name' => $project->getUniqueName(),
                'projectTypeId' => $project->payload['awork']['project_type_id'],
                'projectStatusId' => $project->payload['awork']['project_status_id'],
                'projectTemplateId' => $project->payload['awork']['project_template_id'],
                'isBillableByDefault' => true,
            ]
```

**Comment by sebastianrosch** [comment]
Hi @timkley and sorry for the late response. I found out what is happening: Our web app loads the description of the project template into the form so that users can adjust it before creating a project. In those cases it would have been set on the project. Our API does not do this in order to not override the description a user might have adjusted or removed on purpose.

To solve your problem, the best would be to fetch the project template with the id you already have and pass the project description of the template when creating the project

I hope this helps.

**Comment by timkley** [comment]
Hi @sebastianrosch,

thank you for your detailed answer, that makes sense. Seems like my users thought they saw the description getting populated by the API.

Closing :)
