### ISSUE TITLE
[Question]: Filter for timeentries not working

### ISSUE THREAD

**Issue by kappayero** [awork-io/awork#47]
### What is your question?

Hello. I'm currently trying to get all time entries whose start date lies within a certain time range. I've currently managed to retrieve all time entries without using filters, but when trying to filter with startDateUtc, all entries are retrieved again, as if there were no filter applied.

I am using SoapUI to test the endpoint using the following URL:

https://chartreuse-singular-idols.awork.io/api/v1/timeentries?startDateUtc=2022-03-03T00%3A00%3A00.000Z&endDateUtc=2022-03-06T00%3A00%3A00.000Z&page=1&orderby=CreatedOn&pageSize=100

and as well:
https://chartreuse-singular-idols.awork.io/api/v1/timeentries?startDateUtc=2022-03-03T00%3A00%3A00.000Z

The following trace-id were generated after the calls:
First Call:
trace-id: 2c40f4a807c2147c
Second call:
trace-id: 2aad67a29acf17bb

I understand that I might not be filtering properly. In that case, how can I apply the filter mentioned beforehand?

Thank you very much.

### Do you have a trace id of the call?

trace-id: 2c40f4a807c2147c
trace-id: 2aad67a29acf17bb

**Comment by IanBuck-dev** [comment]
Hello @kappayero,
in order to filter by the dates you need to apply a filterby=... expression to the query. You can find a detailed description here: https://developers.awork.io/filtering

In short I think you need to use:
https://chartreuse-singular-idols.awork.io/api/v1/timeentries?filterby=startDateUtc ge datetime'2022-03-03T00:00' and endDateUtc le datetime'2022-03-06T00:00'

Let me know if this helps!

Best wishes
Ian
