### ISSUE TITLE
[Bug]: Task added webhook doesn't send assignee(s)

### ISSUE THREAD

**Issue by timkley** [awork-io/awork#80]
### What happened?

When using the "Task added" webhook, the model that is sent seems to be incomplete.

Although an assignee was selected, the model which is sent in the Webhook doesn't contain the given assignee.

When looking at the dev tools it seems that two calls are happening when adding a task, one for adding the task and another for adding the assignees.

I'd argue that this is not the expected behaviour of the "task added" webhook. This means that we would need two webhooks or set a small timer to call the API again to get the correct data.

Can this be changed to either one API call so the sent model can be correct from the start or the sending of the webhook be "delayed" to provide accurate data?

### What is the trace id of the call?

2566046dc084a2a3 <- task added

**Comment by nilzzzzzz** [comment]
Hi @timkley ,

for us the creation of the task and the assignment of user/users are two business operations. (also two api calls made). First Post Task and then post SetAssignees. That is the reason we are sending two webhooks instead of one.

We know this is not optimal for some use cases, but currently have no way to prevent that behavior. 

We will track this issue as an improvement, we could move the set assignees to the post of the task - we do the same already for the task lists. 

Best

Nils

**Comment by timkley** [comment]
@nilzzzzzz thank you for your reply.

We tried working around by listening for the `taskassignment_added` webhook and pulling the task with the provided `taskId`. Unfortunately there seems to be some kind of race condition because the assignee is still empty when fetching the task directly from the webhook call.

I would've assumed the webhook is only fired _after_ any writing is done. When I fetch the resource a few seconds later manually the assignee is assigned correctly.

Do you have any ideas how to get around this issue (without just waiting a few seconds before handling the webhook)?
